 /home/astro/magnan/Repository_Stage_3A/find_best_kernel.py:5: UserWarning:matplotlib.pyplot as already been imported, this call will have no effect.
 /home/astro/magnan/.local/lib/python3.7/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1
Traceback (most recent call last):
  File "/home/astro/magnan/Repository_Stage_3A/find_best_kernel.py", line 142, in <module>
    figure = plt.figure()
  File "/astro/soft/common/gcc/5.4.0/python/3.7.1/lib/python3.7/site-packages/matplotlib/pyplot.py", line 525, in figure
    **kwargs)
  File "/astro/soft/common/gcc/5.4.0/python/3.7.1/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3218, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/astro/soft/common/gcc/5.4.0/python/3.7.1/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1008, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/astro/soft/common/gcc/5.4.0/python/3.7.1/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:49.0"
